apps/ava_core_project/urls.py
from django.conf.urls import include, patterns, url
from django.contrib.auth.decorators import login_required

from apps.ava_core_project import views

urlpatterns = patterns('',
    
    url(r'^$', login_required(views.DashboardView.as_view()), name='index'),
    url(r'^(?P<pk>\d+)/$', login_required(views.ProjectIndexView.as_view()), name='project'),
    url(r'^(?P<pk>\d+)/view/$', login_required(views.ProjectDetailView.as_view()), name='project_view'),
    url(r'^new/$',login_required(views.ProjectCreateView.as_view()),name='project_new'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.ProjectUpdateView.as_view()), name='project_update'),
    url(r'^(?P<pk>\d+)/delete/$', login_required(views.ProjectDeleteView.as_view()), name='project_delete'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dh5bp.urls import urlpatterns as dh5bp_urls
from django.contrib.auth.decorators import login_required
from apps.ava_core_project.views import DashboardView

admin.autodiscover()

handler404 = 'dh5bp.views.page_not_found'
handler500 = 'dh5bp.views.server_error'

urlpatterns = patterns('',
    url(r'^$', login_required(DashboardView.as_view()), name='index'),
    url(r'^ava/', include('apps.ava_core.urls')),
    url(r'^accounts/', include('apps.ava_core_auth.urls')),
    url(r'^project/', include('apps.ava_core_project.urls')),
    url(r'^ldap/', include('apps.ava_core_ldap.urls')),
    url(r'^people/', include('apps.ava_core_people.urls')),
    url(r'^org/', include('apps.ava_core_org.urls')),
    url(r'^graph/', include('apps.ava_vis_graph.urls')),
    url(r'^test/', include('apps.ava_test.urls')),
    url(r'^test/email/', include('apps.ava_test_email.urls')),
    url(r'^test/twitter/', include('apps.ava_test_twitter.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += dh5bp_urls

apps/ava_core_project/models.py
from django.db import models
from apps.ava_core.models import TimeStampedModel, ReferenceModel, ConfigurationModel
from django.contrib.auth.models import User

class Project(TimeStampedModel):
    name=models.CharField(max_length=100)
    user = models.ForeignKey(User)
    description=models.CharField(max_length=300)

    def __unicode__(self):
        return self.name or u''
    
#class ProjectRole(ReferenceModel):
#    pass

class ProjectTeamMembers(TimeStampedModel):
    project=models.ForeignKey('Project')
    user=models.ForeignKey(User)

    def __unicode__(self):
        return self.user or u''
    

apps/ava_core_project/forms.py
from django.forms import ModelForm, Form
from apps.ava_core_project.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('name',  'description')

apps/ava_core_project/views.py
from django.views import generic
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.http import HttpResponseRedirect

from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User
from apps.ava_core_project.models import Project
from apps.ava_core_project.forms import  ProjectForm

class DashboardView(generic.ListView):
    template_name = 'project/home.html'
    context_object_name = 'list'

    def get_queryset(self):
        self.request.session['project']=None 
        return Project.objects.filter(user=self.request.user)


class ProjectIndexView(generic.ListView):
    template_name = 'project/index.html'
    context_object_name = 'list'

    def get_queryset(self):
        self.request.session['project']=None 
        return Project.objects.filter(user=self.request.user)

class ProjectDetailView(generic.DetailView):
    model = Project
    context_object_name = 'project'
    template_name = 'project/view.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        if pk:
            project = get_object_or_404(Project, pk=pk)
            request.session['project']=project.id
        return super(ProjectDetailView,self).get(self, request, *args, **kwargs)

class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'confirm_delete.html'
    success_url = '/project/'

class ProjectCreateView(CreateView):
    model = Project
    template_name = 'project/list_modal.html'
    success_url = '/project/'
    form_class = ProjectForm
    page_title = 'Add a new project'
    button_value = 'Add project'
    item_type = 'project'

    def get_context_data(self, **kwargs):
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        context['form'] = self.get_form_class()
        context['form_title'] = self.page_title
        context['button_value'] = self.button_value
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProjectUpdateView(UpdateView):
    model = Project
    template_name = 'item.html'
    success_url = '/project/'
    form_class = ProjectForm
    page_title = 'Update project details'
    button_value = 'Save changes'

    def get_context_data(self, **kwargs):
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['button_value'] = self.button_value
        return context

apps/ava_core_project/templates/project/home.html
{% extends 'project_base.html' %}

{% block mainpage %}


        <h2 class="sub-header">Current Projects</h2>

    <div class="table-responsive">
{% if list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>

                                <a href="{% url 'project_new' %}" class="glyphicon glyphicon-plus" data-toggle="modal" data-target="#myModal"></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
    {% for item in list %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.description }}</td>
        <td>

          <a href="/project/{{ item.id }}/view/"><button type="button" class="btn btn-primary btn-sm">View</button></a>
          <a href="/project/{{ item.id }}/update/"><button type="button" class="btn btn-primary btn-sm">Update</button></a>
          <a href="/project/{{ item.id }}/delete/"><button type="button" class="btn btn-primary btn-sm">Delete</button></a>
    </tr>
    {% endfor %}
     </tbody>
    </table>
{% else %}
    <p>No projects are available.(</p>
{% endif %}
    

 </div> <!-- end of placeholders -->

{% endblock %}

apps/ava_core_project/templates/project/index.html
{% extends 'base.html' %}
{% block mainpage %}

<div class="page-header">
             <h1>[project] .manage</h1>
</div>
{% if project_list %}
    <table style="margin-left:auto;margin-right:auto">
    {% for project in project_list %}
    <tr>
        <td class="left"><a href="/project/{{ project.id }}/view/">{{ project.name }}</a></td>
        <td><a href="/project/{{ project.id }}/update/">[update]</td>
        <td><a href="/project/{{ project.id }}/delete/">[delete]</td>
    </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No projects are available.</p>
{% endif %}
{% endblock %}

apps/ava_core_project/templates/project/list_modal.html
{% load bootstrap3 %}

<div class="modal-header"> 
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">{{ form_title }}</h4> 
</div> 
<div class="modal-body"> 
    <form action="{% url 'project_new' %}" id="{{ form_id }}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                    <button type="submit" class="btn btn-primary">
                       {{ button_value }}
                    </button>
            {% endbuttons %}
        </form>

</div>
<script> 
    var form_options = { target: '#myModal', success: function() { } };
    $('#new_list_form').ajaxForm(form_options); 
</script> 

apps/ava_core_project/templates/project/view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mainpage %}

   <div class="page-header">



<div class="panel panel-info">
               <div class="panel-heading">
                   <h3 class="panel-title">Project Overview</h3>
               </div>

               <div class="panel-body">
                  <div class="row">
                     <div class="col-md-3 col-lg-3 " align="center">
                         <img width="100" alt="" src="{% static 'images/largebinary.jpg'%}" class="img-circle">
                     </div>
                     <div class=" col-md-9 col-lg-9 ">
                        <table class="table table-user-information">
                            <tbody>
                             <tr>
                                <td>Name:</td>
                                <td>{{ project.name }}</td>
                            </tr>
                            {% if project.description %}
                            <tr>
                                <td>Description:</td>
                                <td>{{ project.description }}</td>
                            </tr>
                            {% endif %}
                            </tbody>
                        </table>
                        <a href="/project/{{ project.id }}/update/" class="btn btn-primary">update</a>
                        <a href="/project/{{ project.id }}/delete/" class="btn btn-primary">delete</a>
                    </div>
                </div> <!-- end of row -->
            </div> <!-- end of panel body -->
        </div> <!-- end of panel -->


<h2>Organisations</h2>
{% if project.organisation_set %}

    <div class="table-responsive">

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Industry</th>
                        <th>Size</th>
                        <th>
                                <a href="{% url 'org_new' %}" class="glyphicon glyphicon-plus"></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
   {% for item in project.organisation_set.all %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.industry }}</td>
                        <td>{{ item.size }}</td>
                        <td>

          <a href="/org/{{ item.id }}/view/"><button type="button" class="btn btn-primary btn-sm">View</button></a>
          <a href="/org/{{ item.id }}/update/"><button type="button" class="btn btn-primary btn-sm">Update</button></a>
          <a href="/org/{{ item.id }}/delete/"><button type="button" class="btn btn-primary btn-sm">Delete</button></a>
    </tr>
    {% endfor %}
     </tbody>
    </table>
{% else %}
    <p>This project does not have any organisations associated with it.</p>
{% endif %}

{% endblock %}